package pacote;
// Generated 14/04/2015 21:35:40 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servidor generated by hbm2java
 */
@Entity
@Table(name="Servidor"
    ,catalog="RH"
)
public class Servidor  implements java.io.Serializable {


     private String matriculaSiape;
     private String nome;
     private Integer setor;
     private String nomeMãe;
     private String nomePai;
     private String senha;
     private String email;
     private String perfil;
     private Boolean sexo;
     private Date dataNascimento;
     private String naturalidade;
     private String natUf;
     private String nacionalidade;
     private String escolaridade;
     private String estadoCivil;
     private String tipoSanguíneo;
     private String fatorRh;
     private String cpf;
     private String rg;
     private String rgOrgaoExpedidor;
     private String rgUf;
     private Date dataExpedicao;
     private String tituloEleitor;
     private String teUf;
     private String zona;
     private String sessao;
     private Date dataEmissao;
     private String documentoMilitar;
     private String camOrgaoExpedidor;
     private String camSerie;
     private String carteiraTrabalho;
     private String ctpsSerie;
     private String ctpsUf;
     private String pisPasep;
     private String dataPrimeiroEmprego;
     private String endereco;
     private String numeroComplemento;
     private String bairro;
     private String cep;
     private String cidade;
     private String estado;
     private String telefoneResidencial;
     private String telefoneCelular;
     private String banco;
     private String agencia;
     private String numero;
     private String status;
     private String formacaoExcedente;
     private String formacaoExcedente2;
     private String informacoessComplementares;

    public Servidor() {
    }

	
    public Servidor(String matriculaSiape) {
        this.matriculaSiape = matriculaSiape;
    }
    public Servidor(String matriculaSiape, String nome, Integer setor, String nomeMãe, String nomePai, String senha, String email, String perfil, Boolean sexo, Date dataNascimento, String naturalidade, String natUf, String nacionalidade, String escolaridade, String estadoCivil, String tipoSanguíneo, String fatorRh, String cpf, String rg, String rgOrgaoExpedidor, String rgUf, Date dataExpedicao, String tituloEleitor, String teUf, String zona, String sessao, Date dataEmissao, String documentoMilitar, String camOrgaoExpedidor, String camSerie, String carteiraTrabalho, String ctpsSerie, String ctpsUf, String pisPasep, String dataPrimeiroEmprego, String endereco, String numeroComplemento, String bairro, String cep, String cidade, String estado, String telefoneResidencial, String telefoneCelular, String banco, String agencia, String numero, String status, String formacaoExcedente, String formacaoExcedente2, String informacoessComplementares) {
       this.matriculaSiape = matriculaSiape;
       this.nome = nome;
       this.setor = setor;
       this.nomeMãe = nomeMãe;
       this.nomePai = nomePai;
       this.senha = senha;
       this.email = email;
       this.perfil = perfil;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.naturalidade = naturalidade;
       this.natUf = natUf;
       this.nacionalidade = nacionalidade;
       this.escolaridade = escolaridade;
       this.estadoCivil = estadoCivil;
       this.tipoSanguíneo = tipoSanguíneo;
       this.fatorRh = fatorRh;
       this.cpf = cpf;
       this.rg = rg;
       this.rgOrgaoExpedidor = rgOrgaoExpedidor;
       this.rgUf = rgUf;
       this.dataExpedicao = dataExpedicao;
       this.tituloEleitor = tituloEleitor;
       this.teUf = teUf;
       this.zona = zona;
       this.sessao = sessao;
       this.dataEmissao = dataEmissao;
       this.documentoMilitar = documentoMilitar;
       this.camOrgaoExpedidor = camOrgaoExpedidor;
       this.camSerie = camSerie;
       this.carteiraTrabalho = carteiraTrabalho;
       this.ctpsSerie = ctpsSerie;
       this.ctpsUf = ctpsUf;
       this.pisPasep = pisPasep;
       this.dataPrimeiroEmprego = dataPrimeiroEmprego;
       this.endereco = endereco;
       this.numeroComplemento = numeroComplemento;
       this.bairro = bairro;
       this.cep = cep;
       this.cidade = cidade;
       this.estado = estado;
       this.telefoneResidencial = telefoneResidencial;
       this.telefoneCelular = telefoneCelular;
       this.banco = banco;
       this.agencia = agencia;
       this.numero = numero;
       this.status = status;
       this.formacaoExcedente = formacaoExcedente;
       this.formacaoExcedente2 = formacaoExcedente2;
       this.informacoessComplementares = informacoessComplementares;
    }
   
     @Id 

    
    @Column(name="MatriculaSIAPE", unique=true, nullable=false, length=7)
    public String getMatriculaSiape() {
        return this.matriculaSiape;
    }
    
    public void setMatriculaSiape(String matriculaSiape) {
        this.matriculaSiape = matriculaSiape;
    }

    
    @Column(name="Nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="Setor")
    public Integer getSetor() {
        return this.setor;
    }
    
    public void setSetor(Integer setor) {
        this.setor = setor;
    }

    
    @Column(name="NomeMãe", length=100)
    public String getNomeMãe() {
        return this.nomeMãe;
    }
    
    public void setNomeMãe(String nomeMãe) {
        this.nomeMãe = nomeMãe;
    }

    
    @Column(name="NomePai", length=100)
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }

    
    @Column(name="Senha", length=100)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="Email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Perfil", length=100)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="Sexo")
    public Boolean getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Boolean sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataNascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="Naturalidade", length=100)
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

    
    @Column(name="NatUf", length=2)
    public String getNatUf() {
        return this.natUf;
    }
    
    public void setNatUf(String natUf) {
        this.natUf = natUf;
    }

    
    @Column(name="Nacionalidade", length=100)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="Escolaridade", length=100)
    public String getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }

    
    @Column(name="EstadoCivil", length=100)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="TipoSanguíneo", length=2)
    public String getTipoSanguíneo() {
        return this.tipoSanguíneo;
    }
    
    public void setTipoSanguíneo(String tipoSanguíneo) {
        this.tipoSanguíneo = tipoSanguíneo;
    }

    
    @Column(name="FatorRH", length=5)
    public String getFatorRh() {
        return this.fatorRh;
    }
    
    public void setFatorRh(String fatorRh) {
        this.fatorRh = fatorRh;
    }

    
    @Column(name="CPF", length=11)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="RG", length=15)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="RgOrgaoExpedidor", length=10)
    public String getRgOrgaoExpedidor() {
        return this.rgOrgaoExpedidor;
    }
    
    public void setRgOrgaoExpedidor(String rgOrgaoExpedidor) {
        this.rgOrgaoExpedidor = rgOrgaoExpedidor;
    }

    
    @Column(name="RgUf", length=2)
    public String getRgUf() {
        return this.rgUf;
    }
    
    public void setRgUf(String rgUf) {
        this.rgUf = rgUf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataExpedicao", length=10)
    public Date getDataExpedicao() {
        return this.dataExpedicao;
    }
    
    public void setDataExpedicao(Date dataExpedicao) {
        this.dataExpedicao = dataExpedicao;
    }

    
    @Column(name="TituloEleitor", length=15)
    public String getTituloEleitor() {
        return this.tituloEleitor;
    }
    
    public void setTituloEleitor(String tituloEleitor) {
        this.tituloEleitor = tituloEleitor;
    }

    
    @Column(name="TeUF", length=2)
    public String getTeUf() {
        return this.teUf;
    }
    
    public void setTeUf(String teUf) {
        this.teUf = teUf;
    }

    
    @Column(name="Zona", length=100)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    
    @Column(name="Sessao", length=100)
    public String getSessao() {
        return this.sessao;
    }
    
    public void setSessao(String sessao) {
        this.sessao = sessao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataEmissao", length=10)
    public Date getDataEmissao() {
        return this.dataEmissao;
    }
    
    public void setDataEmissao(Date dataEmissao) {
        this.dataEmissao = dataEmissao;
    }

    
    @Column(name="DocumentoMilitar", length=100)
    public String getDocumentoMilitar() {
        return this.documentoMilitar;
    }
    
    public void setDocumentoMilitar(String documentoMilitar) {
        this.documentoMilitar = documentoMilitar;
    }

    
    @Column(name="CamOrgaoExpedidor", length=10)
    public String getCamOrgaoExpedidor() {
        return this.camOrgaoExpedidor;
    }
    
    public void setCamOrgaoExpedidor(String camOrgaoExpedidor) {
        this.camOrgaoExpedidor = camOrgaoExpedidor;
    }

    
    @Column(name="CamSerie", length=100)
    public String getCamSerie() {
        return this.camSerie;
    }
    
    public void setCamSerie(String camSerie) {
        this.camSerie = camSerie;
    }

    
    @Column(name="CarteiraTrabalho", length=100)
    public String getCarteiraTrabalho() {
        return this.carteiraTrabalho;
    }
    
    public void setCarteiraTrabalho(String carteiraTrabalho) {
        this.carteiraTrabalho = carteiraTrabalho;
    }

    
    @Column(name="CtpsSerie", length=100)
    public String getCtpsSerie() {
        return this.ctpsSerie;
    }
    
    public void setCtpsSerie(String ctpsSerie) {
        this.ctpsSerie = ctpsSerie;
    }

    
    @Column(name="CtpsUF", length=100)
    public String getCtpsUf() {
        return this.ctpsUf;
    }
    
    public void setCtpsUf(String ctpsUf) {
        this.ctpsUf = ctpsUf;
    }

    
    @Column(name="PisPasep", length=100)
    public String getPisPasep() {
        return this.pisPasep;
    }
    
    public void setPisPasep(String pisPasep) {
        this.pisPasep = pisPasep;
    }

    
    @Column(name="DataPrimeiroEmprego", length=100)
    public String getDataPrimeiroEmprego() {
        return this.dataPrimeiroEmprego;
    }
    
    public void setDataPrimeiroEmprego(String dataPrimeiroEmprego) {
        this.dataPrimeiroEmprego = dataPrimeiroEmprego;
    }

    
    @Column(name="Endereco", length=100)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="NumeroComplemento", length=100)
    public String getNumeroComplemento() {
        return this.numeroComplemento;
    }
    
    public void setNumeroComplemento(String numeroComplemento) {
        this.numeroComplemento = numeroComplemento;
    }

    
    @Column(name="Bairro", length=100)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="CEP", length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="Cidade", length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="Estado", length=100)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="TelefoneResidencial", length=100)
    public String getTelefoneResidencial() {
        return this.telefoneResidencial;
    }
    
    public void setTelefoneResidencial(String telefoneResidencial) {
        this.telefoneResidencial = telefoneResidencial;
    }

    
    @Column(name="TelefoneCelular", length=100)
    public String getTelefoneCelular() {
        return this.telefoneCelular;
    }
    
    public void setTelefoneCelular(String telefoneCelular) {
        this.telefoneCelular = telefoneCelular;
    }

    
    @Column(name="Banco", length=100)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

    
    @Column(name="Agencia", length=100)
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }

    
    @Column(name="Numero", length=100)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="Status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="FormacaoExcedente", length=100)
    public String getFormacaoExcedente() {
        return this.formacaoExcedente;
    }
    
    public void setFormacaoExcedente(String formacaoExcedente) {
        this.formacaoExcedente = formacaoExcedente;
    }

    
    @Column(name="FormacaoExcedente2", length=100)
    public String getFormacaoExcedente2() {
        return this.formacaoExcedente2;
    }
    
    public void setFormacaoExcedente2(String formacaoExcedente2) {
        this.formacaoExcedente2 = formacaoExcedente2;
    }

    
    @Column(name="InformacoessComplementares", length=100)
    public String getInformacoessComplementares() {
        return this.informacoessComplementares;
    }
    
    public void setInformacoessComplementares(String informacoessComplementares) {
        this.informacoessComplementares = informacoessComplementares;
    }




}


